sudo: false
language: java
jdk:
- oraclejdk8
before_install:
  - git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
  - cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - secure: cQhktFm8glMAGibNPVsjvPIu9NiOcm0oTqhwGupaTvJdiA8rcrpEt+xhkqiD34Ps18j1BsO4Un96i2y8xiR4mpRx9/PN5s5ynwKuENGM1S9MAnT0NRgW9dKe8FTHK0SLV5O1muNOhPprCIE0wS+oCI+1M+q9jO1ba0Rsbiy/l5kEzcge4I50gAqR/P7wkZTyF/67jJR5K/69X14ZaQwS0GRm8FDJQNJ0bLoSrzJMduT+6W2FxKkP23sqVKB/JzdNgtFBXhr+duEM3/mZnjcLZzJbMHEGZmTPFXYpUxKL4Wh0sjzxlhxspSsyNa1oO4RTFRA9yyC3TwfeNYt5Z/mkyvwWFy/MKpVce6PyakJs6cHQ95IIdeKRzJFVF+1TopxXBgIE2V9+nT7Mf1VdG5i4Amz0F9EBFDrjQ+GzsjnAI5BvIasOnKSnIqwQVLbRDMbCr3TjBXlrtD1WIHZknPKgtRxMKNSe6xi8YaszVewyBiAU6KHLVsRghQ565PeymxRPpvQbHPlhzFrtiA4UrI1YIhzpG/S5X8jsfgUvkRqFflSznddDRGK0ZvupoYjzhwSiJYwd0qe67OgevSeGo3++pPTlb2FBpD684lVmtQnD/FV8aOaBQ8oyCxl4MsNkie/CD+lvblkaYu7b/0ekzxn7tIX469gqqQmTKN1ifdq3BTs=
  - secure: Zqt6SKmWHC1bn8tGyupeq9+4N/vdCNrM3MnThF/EDb9fLaSKrSwpV8bortvVO9d8ulYNVrFVRcLEzafRFOzn5W6tlzIt8A5js6tKaWw/t9nLQ2zIjf5Fn5YEQWZrr6/mR0/SXSbrRPunVCzVpWawwbvnH8C7DQYV5/bEXncaXOwToizoqmi8bTPpOSh78h3In1UE0sn5Z+qm6HSEbTDnrQVGe1htOaDjFLDBK7k8NiYiTHdIPx67Ui5i7HFKOF/jNs9KzPwJto26yCxEO7yfSfJIQ9mWNDBxaBaHolc/t5oDdycRFaLTNHTN3ZQGcrFg3NESFVh5ArcClS3Q20Srpb/g0pmLjTuEKC/xaLsXf0nCvPLaz6+Xc5bugcX4SpfUX/Y04R2K+I4V8N3lAHZ6C3Anx0fYPFQe5yXy7mJSc0XdZLRnTJ6+L+xqzMK6HfnqhU33mJJ7rYLALRgNqkklBPwjUGFXsUaxvuKqvklINx7uu0pZtwfbzMlRGGX0q3xy8MNzR/lA5nlWzpa26H15pFwGB1K+I4CcTIydLuO58vjx3wAbqvkr8gLs19PL3kFDE6aPqSdT/7A/Mn9ZudpCTGDptfJpSdtxUcnz0g88RUMkAlh0QwNm02+TmKv+o4M6kxtW4Tad0Sra7ljOinYl/WgTXU82uw/VZsMFlzhaPb4=
